# This configuration file is for test purpose
entryFile = "test/server/index.ts"
servicesFile = "test/server/services/index.ts"
schemaFile = "test/server/schema.json"
outputFile = "test/dist/index.js"
