packages:
  - packages/gravity
  - packages/create-gravity
  - packages/gravity-svelte
  - packages/gravity-svelte-kit
  - packages/gravity-react
  - packages/gravity-solid
  - packages/gravity-next
  - packages/gravity-vue
  - packages/gravity-nuxt
  - packages/gravity-prisma
