# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16

      # /install
      - uses: actions/cache@v2
        id: pnpm-cache
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-modules-${{ matrix.node-version }}-${{ hashFiles('**/package.json') }}
      - name: Install dependencies
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.30.1
          run_install: true
          run_install.cwd: core
      # install/

      - name: Build
        run: npm run build --prefix core
#      - run: npm test

  publish-npm:
    if: github.event_name == 'push'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm publish --prefix core/package
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
