# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: NPM Package

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      # # /install
      - uses: actions/cache@v2
        id: pnpm-cache
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-modules-${{ matrix.node-version }}-${{ hashFiles('**/package.json') }}
      - name: Install dependencies
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.30.1
          run_install: true
      # # install/

      # - name: Install
      #   run: npm i --prefix core
      - name: Deploy
        run: npm run deploy
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  # publish:
  #   if: github.event_name == 'push'
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v2
  #       with:
  #         node-version: 16
  #         registry-url: https://registry.npmjs.org/
  #     # /install
  #     - uses: actions/cache@v2
  #       id: pnpm-cache
  #       with:
  #         path: ~/.pnpm-store
  #         key: ${{ runner.os }}-modules-${{ matrix.node-version }}-${{ hashFiles('**/package.json') }}
  #     - name: Install dependencies
  #       uses: pnpm/action-setup@v2.0.1
  #       with:
  #         version: 6.30.1
  #         run_install: true
  #     # install/
  #     - run: npm publish core/package
  #       env:
  #         NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
